name: ${project.name}
main: com.thevoxelbox.voxelguest.VoxelGuest
authors: [MikeMatrix, Monofraps, thedeadlybutter]
version: ${project.build.version}
website: ${project.url}
description: ${project.description}
commands:
  greylist:
    aliases: [graylist, gl]
    permission: voxelguest.greylist.greylist
  ungreylist:
    aliases: [ungraylist, ugl]
    permission: voxelguest.greylist.ungreylist
  vgregion:
    permission: voxelguest.regions.modifyregion
  ban:
    aliases: [vban]
    permission: voxelguest.asshat.ban
  banreason:
    aliases: [vbanreason]
    permission: voxelguest.asshat.banreason
  freeze:
    aliases: [vfreeze]
    permission: voxelguest.asshat.freeze
  kick:
    aliases: [vkick]
    permission: voxelguest.asshat.kick
  mute:
    aliases: [vmute, gag, vgag]
    permission: voxelguest.asshat.mute
  soapbox:
    aliases: [vsoapbox]
    permission: voxelguest.asshat.soapbox
  unban:
    aliases: [vunban]
    permission: voxelguest.asshat.unban
  unmute:
    aliases: [vunmute]
    permission: voxelguest.asshat.unmute
  who:
    aliases: [who, vwho, list]
    permission: voxelguest.general.who
  fakequit:
    aliases: [fakequit, fq]
    permission: voxelguest.general.fakequit
  vanish:
    aliases: [vanish, vvanish, van]
    permission: voxelguest.general.vanish
  ep:
    aliases: [ep]
    permission: voxelguest.general.ep
  sys:
    aliases: [sys, system]
    permission: voxelguest.general.sys
  vpg:
    aliases: [vpg, vpromote]
    permission: voxelguest.general.vpg
  vtp:
    aliases: [vtp, vteleport]
    permission: voxelguest.general.vtp