name: ${project.name}
main: com.thevoxelbox.voxelguest.VoxelGuest
authors: [MikeMatrix, Monofraps, thedeadlybutter]
version: ${project.version}
website: ${project.url}
description: ${project.description}