name: ${project.name}
main: com.thevoxelbox.voxelguest.VoxelGuest
authors: [MikeMatrix, Monofraps, thedeadlybutter]
version: ${project.version}
website: ${project.url}
description: ${project.description}
commands:
  greylist:
    aliases: [graylist]
    permission: voxelguest.greylist.greylist
  ungreylist:
    aliases: [ungraylist]
    permission: voxelguest.greylist.ungreylist