name: VoxelGuest
main: com.thevoxelbox.voxelguest.VoxelGuest
author: VoxelPlugineering
version: 4.0.0a
website: http://voxelwiki.com/minecraft/VoxelGuest

commands:
  afk:
    aliases: [vafk]
    usage: /<command>
  opass:
    aliases: [offlinepass, offlinepassword]
    usage: /<command> (password)
  opardon:
    aliases: [offlinepardon]
    usage: /<command> [user]
  who:
    aliases: [online, list, readlist]
    usage: /<command>
