# #########################################
# #
# # =============================
# # VOXELGUEST 4 PERMISSIONS FILE
# #
# # Built by: psanker
# # =============================
# #
# # This is a standard permissions system for VoxelGuest, which VoxelGuest handles after all
# # other systems are disregarded OR the config explicitly says to use the VG perms system.
# # This file accepts both UNIX LF line endings ("\n") and Windows line endings ("\r\n").
# #
# # BE SURE TO USE SPACES AND NOT TABS. Use a good text editor to edit this file.
# # Notepad++ is recommended for Windows, and TextMate is recommended for Mac.
# #
# # Comments start with a pound sign (like the beginning of this and the above lines).
# # The YAML processor will ignore these lines. To verify your YAML syntax, please use
# # http://yaml-online-parser.appspot.com/
# #
# # Please note: There is no multi-world and multi-group support
# #
# #########################################


group:
  admin:
    permissions:
    - '*'
user:
  psanker:
    group: admin
